### ISSUE TITLE
User Journey - Join as a member of an organisation

### ISSUE THREAD

**Issue by BenNewman90** [ReadWithAudrey/readwithaudrey#339]
- [x] Filter by organisation. "Are you joining as part of an organisation" - Yes or no option, followed by manually typing in the code associated with the organisation. Error message if code not accepted. Expandable answer/question like Form 3. #341 
- [x] Create a dummy organisation, and filter the data into that Airtable. Server will be linked to the organisation code (not the name), so the backend does not need updating each time an organisation is added. #342
- [x] In Airtable, create an Audrey Admin base, with Ambassadors and Content Creators as a table #342
- [x] Create a dummy main email address, and use it to send the SendGrid email from #344
- [x] Have the server check all the bases for feedback, pairing and lead email and send from the correct ambassadors email address. Welcome email to also send from the correct ambassadors email address #344
