### ISSUE TITLE
Back-end Full Form Capture

### ISSUE THREAD

**Issue by DenisKent** [ReadWithAudrey/readwithaudrey#96]
Full Form Capture executed at the end of Form Part 3. Need to build a route to do the following:

- [x] Send user data to users table #93

- [ ] Tell user their registration has been unsuccessful, if it has been unsuccessful.

- [ ] Add user to mailchimp mailinglist for a welcome email #94

- [ ] Testing for full form capture, data validation too #97
